/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Admin.DSNhanVien.dialog;

import Component.CheckTruongDuLieu;
import Controller.NVController.DSNVController;
import View.Admin.DSNhanVien.DSNhanVienView;
import View.Admin.MainAdminView;
import javax.swing.JOptionPane;

/**
 *
 * @author vduct
 */
public class XoaNV extends javax.swing.JDialog {

    /**
     * Creates new form XoaNV
     */
    private MainAdminView mainAdminView;
    private DSNhanVienView dSNVView;
    
    public XoaNV(MainAdminView Frame, DSNhanVienView FrameNVView, boolean modal) {
        initComponents();
        this.mainAdminView = Frame;
        this.dSNVView = FrameNVView;
        this.setSize(400, 175);
        this.setResizable(false);
        this.setTitle("Xóa chủ hộ");
        this.setModalityType(DEFAULT_MODALITY_TYPE.APPLICATION_MODAL);
        this.setLocationRelativeTo(null);
        
        if(dSNVView.getNV() != null){
            cccdTf.setText(dSNVView.getNV().getCCCD());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hủyBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        cccdLbl = new javax.swing.JLabel();
        cccdTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        hủyBtn.setText("Hủy");
        hủyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hủyBtnActionPerformed(evt);
            }
        });

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cccdLbl.setText("Nhập CCCD cần xóa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cccdLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hủyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cccdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cccdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cccdLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hủyBtn)
                    .addComponent(okBtn))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hủyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hủyBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_hủyBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        //Kiểm tra Text field có bị trống không
        if(cccdTf.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng không được bỏ trống");
        }else if(!(CheckTruongDuLieu.KtraCCCD(cccdTf.getText()))){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng CCCD (phải là các chữ số có đủ 12 ký tự)");
        }else if(!(new CheckTruongDuLieu().KtraCCCDTonTai(cccdTf.getText()))){
            JOptionPane.showMessageDialog(this, "Chủ hộ có CCCD: " + cccdTf.getText() + " không tồn tại!");
        }else{
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xóa chủ hộ có CCCD: " + cccdTf.getText() + " không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                new DSNVController().XoaChuHo(cccdTf.getText());
                JOptionPane.showMessageDialog(this, "Đã xóa chủ hộ có CCCD: " + cccdTf.getText() + " thành công!");

                mainAdminView.CapNhatBangTrangThai();
                mainAdminView.setForm(new DSNhanVienView(mainAdminView));

                this.dispose();
            }
        }
    }//GEN-LAST:event_okBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cccdLbl;
    private javax.swing.JTextField cccdTf;
    private javax.swing.JButton hủyBtn;
    private javax.swing.JButton okBtn;
    // End of variables declaration//GEN-END:variables
}
